"""Asset credits: CREDITS.md generated from docs/credits/, and the check that every LFS asset has an entry.

docs/AGENT_WORKFLOW.md §10 and docs/decisions/2026-09-28-one-file-per-entry-logs.md. One file per entry,
docs/credits/<asset-slug>.md:

    # Kenney Prototype Textures

    - **Files:** `levels/textures/prototype/**`
    - **Author:** Kenney
    - **Source:** https://kenney.nl/assets/prototype-textures
    - **License:** CC0 1.0
    - **AI generated:** false
    - **Public repo OK:** true

`Files` lists repo-relative globs in backticks (`*` stays inside one folder, `**` crosses folders). More
`- **Field:** value` lines and free text are allowed and copied into CREDITS.md as they are. An entry that covers an
LFS asset also carries the art manifest's provenance (#519): `AI generated` and `Public repo OK`, each `true` or
`false` first (a note may follow), and a public repo takes only `Public repo OK: true`.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from .common import ROOT, Failure, bad, ok, say

CREDITS_DIR = "docs/credits"
OUTPUT = "CREDITS.md"
REQUIRED = ("Files", "Author", "Source", "License")
# The art manifest's ai_generated and public_repo_ok (prime-game-art docs/manifest.md), for an entry that covers an LFS
# asset (#519; addons' entries cover none).
PROVENANCE = ("AI generated", "Public repo OK")
# Third-party code with its own LICENSE file; its images are kept out of LFS (.gitattributes) so CI can load them.
EXEMPT_PREFIX = "addons/"
FIELD_RE = re.compile(r"^- \*\*([A-Za-z][A-Za-z ]*):\*\*\s*(.*)$")
GLOB_RE = re.compile(r"`([^`]+)`")
FIX = "Run: tools\\run.cmd credits (or tools/run.sh credits), and commit CREDITS.md with the entry."
HEADER = """# Credits

<!-- Generated by `tools\\run.cmd credits` from docs/credits/. Edit those files, not this one. -->

Third-party assets and code in this repository, with their authors, sources and licenses. Each section comes from
one file in [docs/credits/](docs/credits/) (docs/AGENT_WORKFLOW.md §10).
"""


@dataclass
class Entry:
    path: str
    title: str
    fields: dict[str, str]
    globs: list[str]
    body: list[str]


@dataclass
class Report:
    errors: list[str] = field(default_factory=list)
    entries: int = 0
    assets: int = 0


def glob_regex(pattern: str) -> re.Pattern[str]:
    """A repo-relative glob as a regex: `*` and `?` stay inside one folder, `**` crosses folders."""
    out, i = [], 0
    while i < len(pattern):
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
        elif pattern.startswith("**", i):
            out.append(".*")
            i += 2
        elif pattern[i] == "*":
            out.append("[^/]*")
            i += 1
        elif pattern[i] == "?":
            out.append("[^/]")
            i += 1
        else:
            out.append(re.escape(pattern[i]))
            i += 1
    return re.compile("".join(out))


def _glob_problem(pattern: str) -> str | None:
    if "\\" in pattern:
        return "use / in paths, not \\"
    if pattern.startswith("/") or re.match(r"^[A-Za-z]:", pattern):
        return "must be relative to the repo root"
    if ".." in pattern.split("/"):
        return "must not contain .."
    return None


def parse(rel: str, text: str) -> tuple[Entry | None, list[str]]:
    """One docs/credits entry. Returns the entry, or None with the reasons."""
    lines = text.removeprefix("﻿").replace("\r\n", "\n").split("\n")
    while lines and not lines[0].strip():
        lines.pop(0)
    if not lines or not lines[0].startswith("# "):
        return None, [f"{rel}: must start with '# <asset name>'"]
    title = lines[0][2:].strip()
    body = lines[1:]
    errors: list[str] = []
    fields: dict[str, str] = {}
    current = ""  # the field an indented continuation line belongs to
    for number, line in enumerate(body, start=2):
        match = FIELD_RE.match(line)
        if not match:
            if current and line.startswith((" ", "\t")) and line.strip():
                fields[current] += " " + line.strip()  # a value wrapped onto the next line
            else:
                current = ""
            continue
        name, value = match.group(1).strip(), match.group(2).strip()
        if name in fields:
            errors.append(f"{rel}:{number}: {name} appears twice")
        fields[name] = value
        current = name
    for name in REQUIRED:
        if not fields.get(name):
            errors.append(f"{rel}: missing '- **{name}:** ...'")
    globs = GLOB_RE.findall(fields.get("Files", ""))
    if fields.get("Files") and not globs:
        errors.append(f"{rel}: Files: put each path or glob in backticks, e.g. `levels/props/crate/**`")
    for pattern in globs:
        problem = _glob_problem(pattern)
        if problem:
            errors.append(f"{rel}: Files: `{pattern}` {problem}")
    if not title:
        errors.append(f"{rel}: the '# ' title is empty")
    while body and not body[-1].strip():
        body.pop()
    while body and not body[0].strip():
        body.pop(0)
    if errors:
        return None, errors
    return Entry(rel, title, fields, globs, body), []


def load(root: Path) -> tuple[list[Entry], list[str]]:
    """All entries, sorted by title, and the problems of the ones that do not parse."""
    folder = root / CREDITS_DIR
    entries: list[Entry] = []
    errors: list[str] = []
    if folder.is_dir():
        for path in sorted(folder.glob("*.md")):
            rel = path.relative_to(root).as_posix()
            entry, problems = parse(rel, path.read_text(encoding="utf-8-sig"))
            errors += problems
            if entry:
                entries.append(entry)
    entries.sort(key=lambda e: (e.title.casefold(), e.path))
    return entries, errors


def _demote(line: str, fenced: bool) -> str:
    return "#" + line if not fenced and re.match(r"^#{1,5} ", line) else line


def render(entries: list[Entry]) -> str:
    """CREDITS.md: the header, then each entry under a `## <title>` heading, with its headings one level down."""
    parts = [HEADER]
    if not entries:
        parts.append("\nNo third-party assets yet.\n")
    for entry in entries:
        fenced = False
        lines = [f"## {entry.title}", ""]
        for line in entry.body:
            if line.startswith("```"):
                fenced = not fenced
            lines.append(_demote(line, fenced))
        parts.append("\n" + "\n".join(lines) + "\n")
    return "".join(parts)


def _git(root: Path, args: list[str], stdin: str | None = None) -> str:
    try:
        res = subprocess.run(
            ["git", *args], cwd=root, input=stdin, capture_output=True, text=True, encoding="utf-8", timeout=60
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise Failure(f"git {args[0]} failed: {exc}") from exc
    if res.returncode != 0:
        raise Failure(f"git {' '.join(args)} exited {res.returncode}: {res.stderr.strip()}")
    return res.stdout


def repo_files(root: Path) -> list[str]:
    """Tracked files plus untracked ones that are not ignored (a new asset counts before its commit)."""
    out = _git(root, ["ls-files", "-z", "--cached", "--others", "--exclude-standard"])
    return sorted({name for name in out.split("\0") if name and (root / name).is_file()})


def lfs_assets(root: Path, files: list[str]) -> list[str]:
    """The files that .gitattributes routes through Git LFS (filter=lfs), outside addons/."""
    if not files:
        return []
    out = _git(root, ["check-attr", "-z", "--stdin", "filter"], stdin="\0".join(files) + "\0")
    fields = out.split("\0")
    assets = []
    for i in range(0, len(fields) - 2, 3):
        path, value = fields[i], fields[i + 2]
        if value == "lfs" and not path.startswith(EXEMPT_PREFIX):
            assets.append(path)
    return sorted(assets)


def flag(value: str) -> bool | None:
    """`true` or `false` at the start of a field's value (a note may follow), else None."""
    words = value.split()
    first = words[0].strip(".,;:()").lower() if words else ""
    return {"true": True, "false": False}.get(first)


def provenance_problems(entry: Entry, covered: list[str]) -> list[str]:
    """An entry that covers LFS assets states the art manifest's provenance, and a public repo takes only
    `public_repo_ok = true`."""
    problems = []
    for name in PROVENANCE:
        if flag(entry.fields.get(name, "")) is None:
            problems.append(
                f"{entry.path}: covers the LFS asset {covered[0]} but has no '- **{name}:** true' or 'false' (the art"
                " manifest's ai_generated and public_repo_ok)"
            )
    if flag(entry.fields.get("Public repo OK", "")) is False:
        problems.append(
            f"{entry.path}: Public repo OK is false: this public repo takes only assets the art manifest marks"
            " public_repo_ok = true"
        )
    return problems


def check(root: Path = ROOT) -> Report:
    """Entries parse, every LFS asset outside addons/ is covered, no glob is stale, CREDITS.md is current."""
    entries, errors = load(root)
    report = Report(errors=list(errors), entries=len(entries))
    files = repo_files(root)
    assets = lfs_assets(root, files)
    report.assets = len(assets)
    patterns = [(entry, glob, glob_regex(glob)) for entry in entries for glob in entry.globs]
    for entry, glob, regex in patterns:
        if not any(regex.fullmatch(name) for name in files):
            folder = glob.rstrip("/") + "/"
            hint = (
                f"it is a folder: write `{folder}**`"
                if any(name.startswith(folder) for name in files)
                else "a typo, or a removed asset"
            )
            report.errors.append(f"{entry.path}: Files: `{glob}` matches no file in the repo ({hint})")
    for entry in entries:
        regexes = [regex for owner, _, regex in patterns if owner is entry]
        covered = [asset for asset in assets if any(regex.fullmatch(asset) for regex in regexes)]
        if covered:
            report.errors += provenance_problems(entry, covered)
    for asset in assets:
        if not any(regex.fullmatch(asset) for _, _, regex in patterns):
            report.errors.append(
                f"{asset}: an LFS asset without a credits entry: add {CREDITS_DIR}/<asset-slug>.md "
                "(Files, Author, Source, License, AI generated, Public repo OK)"
            )
    if not errors:
        current = root / OUTPUT
        text = current.read_text(encoding="utf-8-sig").replace("\r\n", "\n") if current.is_file() else None
        if text != render(entries):
            report.errors.append(f"{OUTPUT} is {'missing' if text is None else 'out of date'}: {FIX}")
    return report


def count(n: int) -> str:
    return f"{n} {'entry' if n == 1 else 'entries'}"


def main(root: Path = ROOT) -> int:
    """`credits`: write CREDITS.md from docs/credits/."""
    say("credits")
    entries, errors = load(root)
    if errors:
        for line in errors:
            bad(line)
        say("credits: FAILED (CREDITS.md not written)")
        return 1
    text = render(entries)
    path = root / OUTPUT
    old = path.read_bytes() if path.is_file() else None
    if old == text.encode("utf-8"):
        ok(f"{OUTPUT} is up to date ({count(len(entries))})")
    else:
        path.write_bytes(text.encode("utf-8"))
        ok(f"wrote {OUTPUT} ({count(len(entries))})")
    say("credits: passed")
    return 0
